<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>

html, body {
    width: 94%;
    height: 100%;
    margin: 0 auto;
    padding: 0;
    background: #fff;
    color: #000;
    font-family: sans-serif;
    font-size: 12px;
}

strong { font-size: 1.5em; }

.left { float: left; }
.right { float: right; }

.text-left { text-align: left !important; }
.text-right { text-align: right !important; }
.text-center { text-align: center !important; }

.col50 { width: 50%; }
.col33 { width: 33%; }

.header {
    text-align: right;
    padding-top: 4em;
}

.footer {
    font-size: 0.75em;
    margin-top: 3em;
}

table {
    width: 100%;
    border-collapse: collapse;
}
table th {
    font-weight: normal;
}

table.grid th, table.grid td {
    border: 1px solid #000;
    vertical-align: text-top;
}
table.grid th {
    text-align: left;
    background: #eee;
}

table.contractors {
    font-size: 1.2em;
    margin-top: 6em;
}
table.contractors td, table.contractors th {
    padding: 5px;
}
table.contractors td p {
    line-height: 1.5em;
    padding: 0.2em;
    margin: 0;
}
table.contractors td p b {
    font-size: 1.2em;
}

table.items {
    font-size: 0.95em;
    margin-top: 6em;
}
table.items td, table.items th {
    padding: 6px;
}

table.details {
    margin-top: 6em;
}
table.details td {
    padding: 0.2em 1.5em;
}

table.signs {
    margin-top: 9em;
}

</style>
</head>
<body>

<div class="header">
    <img src="<?= $this->asset('fakelogo.png') ?>" style="float: left; width:50%" />
    Faktura VAT nr. / VAT Invoice no: <strong><?= $invoice->invoiceReference ?></strong><br />
    Oryginał / Original<br />
    Miejscowość / Place: <b><?= $invoice->placeOfIssue ?></b><br />
    Data wystawienia / Date of issue: <b><?= $this->date($invoice->dateOfIssue) ?></b><br />
    Data sprzedaży / Date of sell: <b><?= $this->date($invoice->dateOfSell) ?></b><br />
</div>

<table class="grid contractors">
    <thead>
        <tr>
            <th class="col50"><b>Sprzedawca</b> (Seller)</th>
            <th class="col50"><b>Nabywca</b> (Buyer)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <p>
                    <b><?= $invoice->seller->companyName ?></b><br />
                    <?= $invoice->seller->address->street ?><br />
                    <?= $invoice->seller->address->city ?> <?= $invoice->seller->address->postCode ?><br />
                    NIP <?= $invoice->seller->taxReference ?><br />
                    <?= $invoice->seller->extra->Phone ?><br />
                    <?= $invoice->seller->extra->Email ?><br />
                    <?= $invoice->seller->extra->WWW ?><br />
                </p>
            </td>
            <td>
                <p>
                    <b><?= $invoice->buyer->companyName ?></b><br />
                    <?= $invoice->buyer->address->street ?><br />
                    <?= $invoice->buyer->address->city ?> <?= $invoice->buyer->address->postCode ?><br />
                    NIP <?= $invoice->buyer->taxReference ?><br />
                    REGON <?= $invoice->buyer->extra->REGON ?><br />
                    KRS <?= $invoice->buyer->extra->KRS ?><br />
                    <?= $invoice->buyer->extra->Phone ?><br />
                </p>
            </td>
        </tr>
    </tbody>
</table>

<table class="grid items">
    <thead>
        <tr>
            <th><b>L.p.</b><br />No</th>
            <th><b>Nazwa towaru lub usługi</b><br />Description</th>
            <th class="text-right"><b>Ilość</b><br />Quantity</th>
            <th class="text-right"><b>J.m.</b><br />Unit</th>
            <th class="text-right"><b>Cena netto</b><br />Net price</th>
            <th class="text-right"><b>Wartość netto</b><br />Net amount</th>
            <th class="text-right"><b>Stawka VAT</b><br />VAT Tax</th>
            <th class="text-right"><b>Kwota VAT</b><br>VAT amount</th>
            <th class="text-right"><b>Wartość brutto</b><br>Total amount</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($invoice->items as $item): ?>
            <tr>
                <td class="text-right"><?= $item->index ?></td>
                <td><?= $item->description ?></td>
                <td class="text-right"><?= $item->quantity ?></td>
                <td class="text-right"><?= $item->unitName ?></td>
                <td class="text-right"><?= $this->money($item->unitNetPrice) ?></td>
                <td class="text-right"><?= $this->money($item->totalNetAmount) ?></td>
                <td class="text-right"><?= $this->percent($item->taxPercentage) ?></td>
                <td class="text-right"><?= $this->money($item->totalTaxAmount) ?></td>
                <td class="text-right"><?= $this->money($item->totalAmount) ?></td>
            </tr>
        <?php endforeach ?>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><b>Razem</b><br />Total</td>
            <td class="text-right"><?= $this->money($invoice->totalNetAmount) ?></td>
            <td></td>
            <td class="text-right"><?= $this->money($invoice->totalNetAmount) ?></td>
            <td class="text-right"><b><?= $this->money($invoice->totalAmount) ?></b></td>
        </tr>
    </tbody>
</table>

<table class="details">
    <tbody>
        <tr>
            <td class="col33 text-right"><strong>Razem do zapłaty:</strong></td>
            <td><strong><strong><?= $this->money($invoice->totalAmount) ?> <?= $invoice->currency ?></strong></strong></td>
        </tr>
        <tr>
            <td class="col33 text-right">Sposób zapłaty:</td>
            <td><?= $invoice->paymentMethod ?></td>
        </tr>
        <tr>
            <td class="col33 text-right">Termin zapłaty:</td>
            <td><?= $this->date($invoice->paymentDueToDate) ?></td>
        </tr>
        <tr>
            <td class="col33 text-right">Numer rachunku:</td>
            <td><?= $invoice->bankAccount->iban ?> <?= $invoice->bankAccount->bankName ?></td>
        </tr>
    </tbody>
</table>

<table class="details">
    <tbody>
        <tr>
            <td class="col33 text-right"><b>Total to pay:</b></td>
            <td><b><?= $this->money($invoice->totalAmount) ?> <?= $invoice->currency ?></b></td>
        </tr>
        <tr>
            <td class="col33 text-right">Payment method:</td>
            <td><?= $invoice->paymentMethod ?></td>
        </tr>
        <tr>
            <td class="col33 text-right">Bank Account (IBAN):</td>
            <td>PL<?= $this->nospaces($invoice->bankAccount->iban) ?></td>
        </tr>
        <tr>
            <td class="col33 text-right">Bank Code (SWIFT):</td>
            <td><?= $invoice->bankAccount->bankSwift ?></td>
        </tr>
        <tr>
            <td class="col33 text-right">Bank Name:</td>
            <td><?= $invoice->bankAccount->bankName ?></td>
        </tr>
        <tr>
            <td class="col33 text-right">Beneficiary Name:</td>
            <td><?= $invoice->bankAccount->beneficiaryName ?></td>
        </tr>
        <tr>
            <td class="col33 text-right">Beneficiary Address:</td>
            <td>
                <?= $invoice->bankAccount->beneficiaryAddress->street ?>,
                <?= $invoice->bankAccount->beneficiaryAddress->city ?>
                <?= $invoice->bankAccount->beneficiaryAddress->postCode ?>
            </td>
        </tr>
    </tbody>
</table>

<table class="details signs">
    <tbody>
        <tr>
            <td class="col50 text-center">..............................................................................</td>
            <td class="col50 text-center">..............................................................................</td>
        </tr>
        <tr>
            <td class="col50 text-center">Wystawił(a): <?= $invoice->issuedBy ?></td>
            <td class="col50 text-center">Odebrał(a): <?= $invoice->signedBy ?></td>
        </tr>
    </tbody>
</table>

<div class="footer">
    <p class="left text-left">
        <?= $invoice->seller->companyName ?><br />
        <?= $invoice->seller->address->city ?> <?= $invoice->seller->address->postCode ?>, ul. <?= $invoice->seller->address->street ?>
    </p>
    <p class="right text-right">
        <?= $invoice->seller->extra->Email ?><br />
        <?= $invoice->seller->extra->WWW ?>
    </p>
</div>

</body>    
</html>
