<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>

html, body {
    width: 94%;
    height: 100%;
    margin: 0 auto;
    padding: 0;
    background: #fff;
    color: #000;
    font-family: sans-serif;
    font-size: 12px;
}

strong { font-size: 1.5em; }

.left { float: left; }
.right { float: right; }

.text-left { text-align: left !important; }
.text-right { text-align: right !important; }
.text-center { text-align: center !important; }

.col50 { width: 50%; }
.col33 { width: 33%; }

.header {
    text-align: right;
}

.footer {
    font-size: 0.7em;
    margin-top: 3em;
}

table {
    width: 100%;
    border-collapse: collapse;
}
table th {
    font-weight: normal;
}

table.grid th, table.grid td {
    border: 1px solid #000;
    vertical-align: text-top;
}
table.grid th {
    text-align: left;
    background: #eee;
}

table.contractors {
    font-size: 1.2em;
    margin-top: 3em;
}
table.contractors td, table.contractors th {
    padding: 5px;
}

table.items {
    font-size: 0.85em;
    margin-top: 3em;
}
table.items td, table.items th {
    padding: 3px;
}

table.details {
    margin-top: 3em;
}
table.details td {
    padding: 0.2em 1.5em;
}

table.signs {
    margin-top: 6em;
}

</style>
</head>
<body>

<div class="header">
    <img src="{{templateDir}}/hellokitty.jpg" style="float: left; width: 15%;" />
    Faktura VAT nr. / VAT Invoice no: <strong>{{uniqueNumber}}</strong><br />
    Oryginał / Original<br />
    Miejscowość / Place: <b>{{origin}}</b><br />
    Data wystawienia / Date of issue: <b>{{dateOfIssue}}</b><br />
    Data sprzedaży / Date of sell: <b>{{dateOfSell}}</b><br />
</div>

<table class="grid contractors">
    <thead>
        <tr>
            <th class="col50"><b>Sprzedawca</b> (Vendor)</th>
            <th class="col50"><b>Nabywca</b> (Purchaser)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <b>{{seller.name}}</b><br />
                {{seller.address.street}}<br />
                {{seller.address.city}} {{seller.address.postCode}}<br />
                {{#seller.details}}
                    {{.}}<br />
                {{/seller.details}}
            </td>
            <td>
                <b>{{buyer.name}}</b><br />
                {{buyer.address.street}}<br />
                {{buyer.address.city}} {{buyer.address.postCode}}<br />
                {{#buyer.details}}
                    {{.}}<br />
                {{/buyer.details}}
            </td>
        </tr>
    </tbody>
</table>

<table class="grid items">
    <thead>
        <tr>
            <th><b>L.p.</b><br />No</th>
            <th><b>Nazwa towaru lub usługi</b><br />Description</th>
            <th class="text-right"><b>Ilość</b><br />Quantity</th>
            <th><b>J.m.</b><br />Unit</th>
            <th class="text-right"><b>Cena netto</b><br />Net price</th>
            <th class="text-right"><b>Wartość netto</b><br />Net amount</th>
            <th class="text-right"><b>Stawka VAT</b><br />VAT Tax</th>
            <th class="text-right"><b>Kwota VAT</b><br>VAT amount</th>
            <th class="text-right"><b>Wartość brutto</b><br>Total amount</th>
        </tr>
    </thead>
    <tbody>
        {{#items}}
            <tr>
                <td class="text-right">{{index}}</td>
                <td>{{description}}</td>
                <td class="text-right">{{quantity}}</td>
                <td>{{unitName}}</td>
                <td class="text-right">{{#money}}{{unitNetPrice}}{{/money}}</td>
                <td class="text-right">{{#money}}{{totalNetAmount}}{{/money}}</td>
                <td class="text-right">{{#percent}}{{taxPercent}}{{/percent}}</td>
                <td class="text-right">{{#money}}{{totalTaxAmount}}{{/money}}</td>
                <td class="text-right">{{#money}}{{totalAmount}}{{/money}}</td>
            </tr>
        {{/items}}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="text-right"><b>Razem</b><br />Total</td>
            <td class="text-right">{{#money}}{{totalNetAmount}}{{/money}}</td>
            <td></td>
            <td class="text-right">{{#money}}{{totalTaxAmount}}{{/money}}</td>
            <td class="text-right"><b>{{#money}}{{totalAmount}}{{/money}}</b></td>
        </tr>
    </tbody>
</table>

<table class="details">
    <tbody>
        <tr>
            <td class="col33 text-right"><strong>Razem do zapłaty:</strong></td>
            <td><strong><strong>{{#money}}{{totalAmount}}{{/money}} PLN</strong></strong></td>
        </tr>
        <tr>
            <td class="col33 text-right">Sposób zapłaty:</td>
            <td>{{paymentMethod}}</td>
        </tr>
        <tr>
            <td class="col33 text-right">Termin zapłaty:</td>
            <td>{{paymentDeadline}}</td>
        </tr>
        <tr>
            <td class="col33 text-right">Numer rachunku:</td>
            <td>{{bankAccount.iban}} {{bankAccount.bankName}}</td>
        </tr>
    </tbody>
</table>

<table class="details">
    <tbody>
        <tr>
            <td class="col33 text-right"><b>Total to pay:</b></td>
            <td><b>{{#money}}{{totalAmount}}{{/money}} PLN</b></td>
        </tr>
        <tr>
            <td class="col33 text-right">Payment method:</td>
            <td>{{paymentMethod}}</td>
        </tr>
        <tr>
            <td class="col33 text-right">Bank Account (IBAN):</td>
            <td>PL{{#nospaces}}{{bankAccount.iban}}{{/nospaces}}</td>
        </tr>
        <tr>
            <td class="col33 text-right">Bank Code (SWIFT):</td>
            <td>{{bankAccount.bankSwift}}</td>
        </tr>
        <tr>
            <td class="col33 text-right">Bank Name:</td>
            <td>{{bankAccount.bankName}}</td>
        </tr>
        <tr>
            <td class="col33 text-right">Beneficiary Name:</td>
            <td>{{bankAccount.beneficiaryName}}</td>
        </tr>
        <tr>
            <td class="col33 text-right">Beneficiary Address:</td>
            <td>{{bankAccount.beneficiaryAddress.street}}, {{bankAccount.beneficiaryAddress.city}} {{bankAccount.beneficiaryAddress.postCode}}</td>
        </tr>
    </tbody>
</table>

<table class="details signs">
    <tbody>
        <tr>
            <td class="col50 text-center">..............................................................................</td>
            <td class="col50 text-center">..............................................................................</td>
        </tr>
        <tr>
            <td class="col50 text-center">Wystawił(a): {{issuedBy}}</td>
            <td class="col50 text-center">Odebrał(a): {{signedBy}}</td>
        </tr>
    </tbody>
</table>

<div class="footer">
    <p class="left text-left">
        DEVGRID Łukasz Cepowski<br />
        Gorzyce 39-432, ul. Norwida 7
    </p>
    <p class="right text-right">
        contact@devgrid.net<br />
        www.devgrid.net
    </p>
</div>

</body>    
</html>
